import { success } from '@/lib/api-response'

// Mock beneficiaires data for the Conseiller espace
const beneficiaires = [
  {
    id: 'b1',
    firstName: 'Amadou',
    lastName: 'Diallo',
    email: 'amadou.diallo@email.com',
    projectTitle: 'Plateforme de livraison locale bio',
    sector: 'Agroalimentaire',
    journeyPhase: 'Structurer',
    progress: 45,
    lastActivity: 'Il y a 2 heures',
    status: 'actif',
    conseiller: 'Sophie Martin',
  },
  {
    id: 'b2',
    firstName: 'Lea',
    lastName: 'Fontaine',
    email: 'lea.fontaine@email.com',
    projectTitle: 'Studio de yoga et bien-etre',
    sector: 'Bien-etre',
    journeyPhase: 'Financer',
    progress: 72,
    lastActivity: 'Il y a 3 heures',
    status: 'actif',
    conseiller: 'Sophie Martin',
  },
  {
    id: 'b3',
    firstName: 'Marc',
    lastName: 'Renaud',
    email: 'marc.renaud@email.com',
    projectTitle: 'Application de gestion locative',
    sector: 'Immobilier',
    journeyPhase: 'Idee',
    progress: 18,
    lastActivity: 'Il y a 1 jour',
    status: 'actif',
    conseiller: 'Sophie Martin',
  },
  {
    id: 'b4',
    firstName: 'Clara',
    lastName: 'Dubois',
    email: 'clara.dubois@email.com',
    projectTitle: 'Boutique de mode ethique en ligne',
    sector: 'Commerce',
    journeyPhase: 'Lancer',
    progress: 88,
    lastActivity: 'Il y a 5 heures',
    status: 'actif',
    conseiller: 'Sophie Martin',
  },
  {
    id: 'b5',
    firstName: 'Karim',
    lastName: 'Benali',
    email: 'karim.benali@email.com',
    projectTitle: 'Service de nettoyage ecologique',
    sector: 'Services',
    journeyPhase: 'Structurer',
    progress: 35,
    lastActivity: 'Il y a 3 jours',
    status: 'en_attente',
    conseiller: 'Sophie Martin',
  },
  {
    id: 'b6',
    firstName: 'Julie',
    lastName: 'Moreau',
    email: 'julie.moreau@email.com',
    projectTitle: 'Cuisine traiteur vegan',
    sector: 'Restauration',
    journeyPhase: 'Idee',
    progress: 10,
    lastActivity: 'Il y a 1 semaine',
    status: 'inactif',
    conseiller: 'Sophie Martin',
  },
  {
    id: 'b7',
    firstName: 'Thomas',
    lastName: 'Leroy',
    email: 'thomas.leroy@email.com',
    projectTitle: "Salle d'escalade et coworking",
    sector: 'Sport',
    journeyPhase: 'Financer',
    progress: 60,
    lastActivity: 'Il y a 12 heures',
    status: 'actif',
    conseiller: 'Sophie Martin',
  },
  {
    id: 'b8',
    firstName: 'Fatima',
    lastName: 'Hassani',
    email: 'fatima.hassani@email.com',
    projectTitle: 'Agence de communication digitale',
    sector: 'Communication',
    journeyPhase: 'Structurer',
    progress: 52,
    lastActivity: 'Il y a 6 heures',
    status: 'actif',
    conseiller: 'Sophie Martin',
  },
  {
    id: 'b9',
    firstName: 'Hugo',
    lastName: 'Petit',
    email: 'hugo.petit@email.com',
    projectTitle: 'Atelier de menuiserie artisanale',
    sector: 'Artisanat',
    journeyPhase: 'Idee',
    progress: 5,
    lastActivity: 'Il y a 2 jours',
    status: 'actif',
    conseiller: 'Sophie Martin',
  },
  {
    id: 'b10',
    firstName: 'Nadia',
    lastName: 'Bouzid',
    email: 'nadia.bouzid@email.com',
    projectTitle: 'Cabinet de coaching scolaire',
    sector: 'Education',
    journeyPhase: 'Financer',
    progress: 78,
    lastActivity: 'Il y a 1 jour',
    status: 'actif',
    conseiller: 'Sophie Martin',
  },
]

export async function GET() {
  return success(beneficiaires, 'Liste des beneficiaires du conseiller')
}
